### ISSUE TITLE
Comments from Josh Soref (2015-07-02)

### ISSUE THREAD

**Issue by AFBarstow** [w3c/webstorage#5]
These comments were submitted by Josh Soref on 2015-07-02:

[[
https://lists.w3.org/Archives/Public/public-webapps/2015JulSep/0019.html

http://www.w3.org/TR/2015/CR-webstorage-20150609/

> Particpate: [sic]
> 
> the event must have its key attribute initialised to the name of the key in question,

`initialized` [About 11,800,000 results] should be spelled as such for
w3c specs (w3c is en-us) instead of
`initialised` [About 553,000 results]

> but require the user to authorise access to local storage areas.

`authorize` [About 80,100,000 results] should be spelled as such for
w3c specs (w3c is en-us) instead of `authorise` [About 6,960,000
results]

> Alternatives that do not require a user-agent-wide per-origin script lock are eagerly sought after.

sought-after [1]

> Each site has its own separate storage area.

area => areas | storage => local storage

> ("must", "should", "may", etc)

etc.

> If the given key does exist in the list, and its value is not equal to value, then it must have its value updated to value. If its previous value is equal to value, then the method must do nothing.
> if the methods did not throw an exception or "do nothing" as defined above

it'd be nice if the above sections underlined/otherwise styled `do nothing`.

> User agents should always avoid deleting data while a script that could access that data is running.

consider a script which does:

var global_state = window.localStorage.getItem("value");
function uses_global_state() { if (global_state == 5) { .... }}
window.setTimeout(uses_global_state, 2000000);

between the script's initial execution, and the firing of the timeout,
is the script considered to be `running`?

[1] http://dictionary.reference.com/browse/sought-after
]]

**Comment by siusin** [comment]
All of these editorial bugs were fixed in the [PR-20151126](https://www.w3.org/TR/2015/PR-webstorage-20151126/).

The script in the last section doesn't seem to be considered as "running" according to the behaviour of the current major browsers.
